<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "littleriver"
 *
 * Auto generated by Extension Builder 2014-01-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Little River Shop',
	'description' => 'Demo Extension Shop for use in Workshops',
	'category' => 'plugin',
	'author' => 'Christian Müller',
	'author_email' => 'christian@kitsunet.de',
	'author_company' => 'Kitsunet',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>